spring.datasource.url=jdbc:postgresql://dpg-d094inh5pdvs738skr7g-a:5432/online_bakery
spring.datasource.username=online_bakery_user
spring.datasource.password=HqorhY52rbaImmp48JBcM1fhzwGfme7K
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

