# Application name
spring.application.name=ECommerceProject

# PostgreSQL database platform
spring.jpa.database=postgresql

# PostgreSQL connection details
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Rap@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate settings
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
