spring.application.name=ECommrceProject
spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://localhost/ecommrceproject
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

